.\" Manpage for jobs.
.TH man 1 "29 February 2020" "1.0" "jobs man page"
.SH NAME
jobs \- display status of jobs in the current session
.SH SYNOPSIS
jobs
.SH DESCRIPTION
The jobs utility shall display the status of jobs that were started
in the current shell environment
.SH OPTIONS
NONE
.SH OPERANDS
NONE
.SH EXAMPLES
.IP "jobs"				
- Display status information for all jobs
.SH AUTHOR
Hiep Le, Slim Ghodhbane

