.\" Manpage for jsum.
.TH man 1 "29 February 2020" "1.0" "jsum man page"
.SH NAME
jsum \- display statistics on all external commands
.SH SYNOPSIS
jsum
.SH DESCRIPTION
The jsum utility shall display the statistics of all external commands that completed since the shell started
.SH OPTIONS
NONE
.SH OPERANDS
NONE
.SH EXAMPLES
.IP "jsum"				
- Display statistics on all completed jobs
.SH AUTHOR
Hiep Le, Slim Ghodhbane

